version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: api_test_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: rustdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/initsql
      - type: tmpfs
        target: /var/lib/postgresql/data

